### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by tynes** [bcoin-org/blgr#9]
This package could use a new release since https://github.com/bcoin-org/blgr/pull/5 was merged in. I am having trouble remotely helping users debug their issues and adding the stacktrace for `logger.error` would be very useful for this.

**Comment by braydonf** [comment]
Have you checked `debug.log`? It will include the stack trace. While I think both should include the stack trace, it is a current work around to that issue.

**Comment by pinheadmz** [comment]
I would really like to see https://github.com/bcoin-org/blgr/pull/8 merged as well, then we can update hsd and bcoin and not have to worry about this module for a while ;-)

**Comment by tynes** [comment]
@braydonf Thank you for that suggestion
@pinheadmz Is #8 ready for review again?

We could also fix https://github.com/bcoin-org/blgr/issues/2 by using https://github.com/bcoin-org/bfile

**Comment by pinheadmz** [comment]
Yeah #8 is ready
